### ISSUE TITLE
Modifier.Macros is empty

### ISSUE THREAD

**Issue by asultanpur** [phalaaxx/milter#1]
The modifier passed to the methods of the milter remain empty. Perhaps you mean `!=` instead of `==` at https://github.com/phalaaxx/milter/blob/1fe05328dc5b10376bfce3d5539a66b94cbf5efb/session.go#L140

**Comment by phalaaxx** [comment]
Yes, you are correct. Thanks for pointing that out, I've fixed it:
https://github.com/phalaaxx/milter/commit/1e2fbc8a9549d9ad90f69058a5cc9aff531343a2
I don't really care about macros in my use cases and that's why I did not see that error earlier, thanks again.
